### ISSUE TITLE
Fazer a revisão da pagina de ferramentas utilizadas pelo time que se encontra na wiki. 

### ISSUE THREAD

**Issue by PauloGoncalvesLima** [Requisitos-de-Software/2020.1-Mia-Ajuda#10]
O link para a pagina na wiki.
    https://github.com/Requisitos-de-Software/2020.1-Ribon/wiki/Ferramentas-utilizadas-pelo-time

**Comment by pedro-cella** [comment]
Revisado.
Só acharia interessante quando o grupo decidir, adicionar a ferramenta a ser utilizada na gravação das apresentações.

**Comment by PauloGoncalvesLima** [comment]
@pedro-cella mudei de alguma coisa para o desenvolvimento de documentos. Vê se esta de boas agora.

**Comment by pedro-cella** [comment]
Acabei de ver, está bem melhor, bem mais objetivo, obrigado.
