### ISSUE TITLE
Fazer a revisão do cronograma de atividades que se encontra na wiki.

### ISSUE THREAD

**Issue by pedro-cella** [Requisitos-de-Software/2020.1-Mia-Ajuda#11]
Link para a página da wiki: https://github.com/Requisitos-de-Software/2020.1-Grupo5/wiki/Cronograma-de-Atividades

**Comment by PauloGoncalvesLima** [comment]
Acho que a data do ponto de controle 2 está errada, não deveria ser dia 10/09 ao invés de 22/09.

**Comment by PauloGoncalvesLima** [comment]
Também porque que se tem datas em baixo de cada ponto de controle mas do lado delas se tem datas definidas ?
Eu não entendi muito bem o que cada uma representa.
Tentando adivinhar seria tipo as embaixo de cada ponto de controle é a data de entrega e as datas definidas foi o tempo de se fazer cada coisa descrita ?

**Comment by andrebdes** [comment]
<img width="1078" alt="Captura de Tela 2020-09-04 às 08 11 33" src="https://user-images.githubusercontent.com/18036847/92233219-42162f80-ee86-11ea-8d48-fdb84b2acaba.png">





Paulo, temos dois encontros do Módulo III - Engenharia de Requisitos - Elicitação de Requisitos(Técnicas, Priorização) nos dias 03/09 e 08/09. 
O encontro do dia 10/09 é para esclarecer eventuais dúvidas sobre a aplicação Elicitação de Requisitos no projeto. 

O esclarecimento das dúvidas é feito antes da data da entrega da apresentação e desses artefatos (28/09/2020) para diminuir a chance de erros na entrega e dar mais tempo para vocês trabalharem nesse conteúdo no projeto. 
Todos os artefatos do projeto exigem tempo para ser bem feitos.

**Comment by pedro-cella** [comment]
Então, o cronograma é estruturado da seguinte forma, os Pontos de Controle indicam quando nós devemos nos reunir para revisar o que está sendo feito, e o que foi feito até a data, se apresenta algum tipo de problema, erro ou qualquer tipo de causalidade que devemos resolver antes da entrega do trabalho, já as datas definidas representam o tempo que cada membro tem de resolver a tarefa que lhe foi passada. Esse cronograma é o inicial para termos uma ideia do que vamos desenvolver após essa primeira apresentação, ela pode e deve apresentar mudanças, visto que eu estabeleci que os pontos de controle devem ser feitos uma semana antes da entrega dos trabalhos, mas isso foi um pré-estabelecimento, quero desenvolver essas datas junto da equipe.
