### ISSUE TITLE
Elicitação de Requisitos - Técnicas

### ISSUE THREAD

**Issue by pedro-cella** [Requisitos-de-Software/2020.1-Mia-Ajuda#24]
## Elicitar as Técnicas dos requisitos

Fazer a elicitação dos requisitos utilizando das técnicas descritas ensinadas.

### Links de recomendados

[Técnicas de Elicitação](https://aprender3.unb.br/pluginfile.php/426730/mod_resource/content/2/Requisitos%20-%20Aula%2007.pdf)

**Comment by pedro-cella** [comment]
Técnicas que podemos utilizar baseando-se na limitação do ambiente EAD:
- Brainstorming;
- Storytelling;
- Prototipação;
- Questionário;
- Introspecção;
- Análise de Protocolo;
- Análise de Discurso;

**Comment by Matheus-AM** [comment]
As tecnicas que não serão utilizadas, e o motivo, são:
- Prototipação: Ao se fazer a "engenharia reversa" o produto final já é totalmente tangível. Portanto, não se torna necessário o uso de um protótipo.
- Análise de Discurso: não há como reunir diretamente com as partes de design, usuarios e cliente.
