### ISSUE TITLE
Verificação - Backlog

### ISSUE THREAD

**Issue by ailamaralves** [Requisitos-de-Software/2020.1-Mia-Ajuda#77]
## Descrição da Issue

Nessa issue espera-se que seja feita a análise de verificação do documento atual e em seguida correções do mesmo.

### Critérios de aceitação

- [x] Atende as sugestões e definições da verificação
- [x] Adicionadas as alterações sugeridas pelo professor
- [x] Documento finalizado e revisado

**Comment by DanilloGS** [comment]
@ailamaralves, @PauloGoncalvesLima, @pedro-cella, @Matheus-AM, Vou precisar de mais alguém pra me ajudar nessa issue

**Comment by PauloGoncalvesLima** [comment]
@DanilloGS Quer fazer quando?

**Comment by DanilloGS** [comment]
@PauloGoncalvesLima pode ser amanhã?
