### ISSUE TITLE
Verificação - Léxico

### ISSUE THREAD

**Issue by ailamaralves** [Requisitos-de-Software/2020.1-Mia-Ajuda#78]
## Descrição da Issue

Nessa issue espera-se que seja feita a análise de verificação do documento atual e em seguida correções do mesmo.

### Critérios de aceitação

- [x] Atende as sugestões e definições da verificação
- [x] Adicionadas as alterações sugeridas pelo professor
- [x] Documento finalizado e revisado

### Versão Atual

[Léxico](https://requisitos-de-software.github.io/2020.1-Mia-Ajuda/#/pages/modeling/lexicon)

**Comment by PauloGoncalvesLima** [comment]
@DanilloGS Quer ajuda nessa issue ?
