### ISSUE TITLE
Gravação da Apresentação 1

### ISSUE THREAD

**Issue by pedro-cella** [Requisitos-de-Software/2020.1-Mia-Ajuda#8]
Os membros devem gravar a primeira apresentação do projeto

**Comment by PauloGoncalvesLima** [comment]
Para poder gravar a tela podemos utilizar o [obs studio](https://obsproject.com/), que da para gravar a tela e se caso tenha uma câmera pode também ser gravada.

**Comment by pedro-cella** [comment]
Estava pensando depois se o próprio Teams não seria mais viável, porque todos já tem o acesso, acho que seria mais adequado do que baixar uma nova ferramenta.
