### ISSUE TITLE
Definição de pontos

### ISSUE THREAD

**Issue by pedro-cella** [Requisitos-de-Software/2020.1-Mia-Ajuda#9]
Determinar sistema de pontuação das issues.

**Comment by PauloGoncalvesLima** [comment]
Você planeja usar o sistema de pontos que já vem no zenhub ou criar um novo? pq eu sinceramente não entendi direito como q funciona esse sistema de pontos.
A única coisas que faz mais sentido na minha cabeça é criar um sistema de pontos onde se relaciona com as labels de baixa, media e alta.

**Comment by pedro-cella** [comment]
Sim, eu iria usar o sistema de pontos que já vem no ZenHub, porque precisa dele para criar o gráfico de burndown.

**Comment by PauloGoncalvesLima** [comment]
Sim, mas o que eu to falando é você planeja usar os pontos que já vem que são os 1, 2, 3, 5, 8, 13, 21, 40 ou criar novos para que se relacionem com as labels?

**Comment by PauloGoncalvesLima** [comment]
https://blog.zenhub.com/how-to-estimate-software-development-projects-with-story-points/
https://blog.zenhub.com/software-estimates/
Achei esses posts do zenhub explicando como que se faz as estimativas. Porque sinceramente para mim aqueles números não faziam sentido algum.

**Comment by pedro-cella** [comment]
Eu pensei em definir os pontos em relação a quantidade de membros que determinada tarefa precisa para ser realizada, menos reuniões, revisões, correção de erros e a gravação das apresentações, essas possuem um valor fixo dos pontos. Logo:

Reuniões - 1 ponto;
Apresentação - 1 ponto;
Revisões - 1 ponto;
Criação de documentos - x pontos (baseado no número de membros que vão trabalhar na tarefa);
Correção de erros(uso da label bug) - 3 pontos
